
server:
  port: 8080

spring:
  application:
    name: zhuang-thymeleaf #指定服务名

jwt:
  config:
    key: itcast
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true
